Use Object.prototype.hasOwnProperty instead of obj.hasOwnProperty
This may be undefined, or the object prototype may not include Object.
This problem was encountered with newer node version(6) or upgraded dependencies.

Fixes `TypeError: object.hasOwnProperty is not a function`